name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  code-quality-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
          architecture: 'x64'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install dependencies
        run: pip install -r requirements/development.txt

      - name: Run code quality analysis tools
        run: tox
